import type { ResourceConfig } from '@/components/admin/resourceTypes';

export const profilConfig: ResourceConfig = {
  key: 'profil',
  endpoint: '/profil',
  label: 'Profil Website',
  labelSingular: 'Profil',
  description: 'Informasi umum, visi, misi, dan sejarah website.',
  singleton: true,
  columns: [],
  fields: [
    { name: 'siteName', label: 'Nama Situs (ID)', type: 'text', required: true, colSpan: 1 },
    { name: 'siteNameEn', label: 'Nama Situs (EN)', type: 'text', colSpan: 1 },
    { name: 'tagline', label: 'Tagline (ID)', type: 'text', colSpan: 1 },
    { name: 'taglineEn', label: 'Tagline (EN)', type: 'text', colSpan: 1 },
    { name: 'logo', label: 'Logo', type: 'image', colSpan: 1 },
    { name: 'heroImage', label: 'Gambar Utama (Hero)', type: 'image', colSpan: 1 },
    { name: 'atraksiHeroImage', label: 'Gambar Hero Atraksi', type: 'image', colSpan: 1 },
    { name: 'budayaHeroImage', label: 'Gambar Hero Budaya', type: 'image', colSpan: 1 },
    { name: 'kulinerHeroImage', label: 'Gambar Hero Kuliner', type: 'image', colSpan: 1 },
    { name: 'penginapanHeroImage', label: 'Gambar Hero Penginapan', type: 'image', colSpan: 1 },
    { name: 'kontakHeroImage', label: 'Gambar Banner Kontak', type: 'image', colSpan: 2 },
    { name: 'about', label: 'Tentang (ID)', type: 'textarea', colSpan: 1 },
    { name: 'aboutEn', label: 'Tentang (EN)', type: 'textarea', colSpan: 1 },
    { name: 'vision', label: 'Visi (ID)', type: 'textarea', colSpan: 1 },
    { name: 'visionEn', label: 'Visi (EN)', type: 'textarea', colSpan: 1 },
    { name: 'mission', label: 'Misi (ID)', type: 'textarea', colSpan: 1 },
    { name: 'missionEn', label: 'Misi (EN)', type: 'textarea', colSpan: 1 },
    { name: 'history', label: 'Sejarah (ID)', type: 'textarea', colSpan: 1 },
    { name: 'historyEn', label: 'Sejarah (EN)', type: 'textarea', colSpan: 1 },
  ],
};

export const kontakConfig: ResourceConfig = {
  key: 'kontak',
  endpoint: '/kontak',
  label: 'Informasi Kontak',
  labelSingular: 'Kontak',
  description: 'Alamat, telepon, dan tautan media sosial.',
  singleton: true,
  columns: [],
  fields: [
    { name: 'address', label: 'Alamat', type: 'text', colSpan: 2 },
    { name: 'phone', label: 'Telepon', type: 'text', colSpan: 1 },
    { name: 'whatsapp', label: 'WhatsApp', type: 'text', colSpan: 1 },
    { name: 'email', label: 'Email', type: 'text', colSpan: 1 },
    { name: 'mapEmbed', label: 'Embed Peta (iframe src)', type: 'text', colSpan: 1 },
    { name: 'instagram', label: 'Instagram', type: 'text', colSpan: 1 },
    { name: 'facebook', label: 'Facebook', type: 'text', colSpan: 1 },
    { name: 'twitter', label: 'Twitter/X', type: 'text', colSpan: 1 },
    { name: 'youtube', label: 'YouTube', type: 'text', colSpan: 1 },
  ],
};
